version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env
    networks:
      - books-club-network


  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - books-club-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 5

  postgres_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '15432:80'
    networks:
      - books-club-network

  api:
    image: waer/microservice-books-club-service:latest
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - auth
      - books
    networks:
      - books-club-network

  auth:
    image: waer/auth-service:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - books-club-network

  books:
    image: waer/books-service:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres
      - auth
    networks:
      - books-club-network


  # redis:
  #   image: redis
  #   command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
  #   env_file:
  #     - .env
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./redis/data:/data

networks:
  books-club-network:
    driver: bridge
