apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  {{- range $key, $val := .Values.env.secret }}
    {{ $key }}: {{ $val | toString | b64enc }}
  {{- end}}
